USE [palooza]
GO

/****** Object:  Table [dbo].[BoostType]    Script Date: 5/11/2016 20:27:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BoostType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](256) NULL,
	[Cost] [int] NULL,
	[ValueChipId] [int] NOT NULL,
 CONSTRAINT [PK_BoostType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BoostType]  WITH CHECK ADD  CONSTRAINT [FK_BoostType_Chip] FOREIGN KEY([ID])
REFERENCES [dbo].[Chip] ([ID])
GO

ALTER TABLE [dbo].[BoostType] CHECK CONSTRAINT [FK_BoostType_Chip]
GO
